#!/bin/bash
ENV_NAME=ionic-mcm

# exit if environment is already active
echo $ATK_ENV | grep "$ENV_NAME" &> /dev/null && echo "Environment $ENV_NAME is already active" && exit

previousNodeVersion=`node --version`
if [ "$previousNodeVersion" != "v14.17.3" ]

	then
	if ! [ -e /usr/local/opt/nvm/nvm.sh ] &> /dev/null
		then
		echo "NVM is not installed -> install now"
		brew install nvm
	fi
	export NVM_DIR=~/.nvm
	source /usr/local/opt/nvm/nvm.sh
	echo "Switching to Node v14.17.3"
	nvm install v14.17.3
	SWITCHED_NODE_VERSION=true
fi
[ -z "$ATK_ENV" ] && export ATK_ENV="$ENV_NAME" || export ATK_ENV="$ATK_ENV,$ENV_NAME"
export PS1="atk-env:$ATK_ENV:\w $ "

function check_global_npm_package {
        echo -n "Checking $1 ..."
        if ! npm list -g "$1" &> /dev/null
                then
                echo " installing ..."
                npm install -g "$1"
        fi
        echo " done"
}

check_global_npm_package cordova@10.0.0
check_global_npm_package @ionic/cli@6.19.0
check_global_npm_package plugman@2.0.0

export CORDOVA_ANDROID_GRADLE_DISTRIBUTION_URL=https://services.gradle.org/distributions/gradle-6.8-bin.zip
echo "Shall I run 'npm install' for you? [Y/n]"
read line
[ "$line" = "n" -o "$line" = "N" ] || npm install

bash
[ -n "$SWITCHED_NODE_VERSION" ] && echo "Switching to previous node version: $previousNodeVersion"
